[package]
name = "squashfs-rust"
version = "0.1.0"
edition = "2021"

[lib]
path = "squashfs.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bincode = "1.3.3"
serde = { version = "1.0.158", features = ["derive"] }
